resolver: lts-6.14
# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
extra-deps:
- th-utilities-0.2.0.1
- store-0.2.1.0
- store-core-0.2.0.0
- th-orphans-0.13.1
- http-client-0.5.0
- http-client-tls-0.3.0
- http-conduit-2.2.0
- optparse-applicative-0.13.0.0
- persistent-2.6
- persistent-template-2.5.1.6
- aeson-1.0.0.0
- semigroups-0.18.2
flags:
  stack:
    hide-dependency-versions: true
  semigroups:
    bytestring-builder: false
packages:
- .
- location:
    git: https://github.com/sjakobi/hpack
    commit: 631c7d67b008fc1387cac03105f9d2acdf2624c1
  extra-dep: true
